"use client";

import { useState, useCallback, useEffect, useMemo } from "react";
import DOMPurify from "dompurify";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

function optimizeSVG(svg: string): string {
  let result = svg;

  // Remove XML declaration
  result = result.replace(/<\?xml[^?]*\?>\s*/gi, "");

  // Remove comments
  result = result.replace(/<!--[\s\S]*?-->/g, "");

  // Remove DOCTYPE
  result = result.replace(/<!DOCTYPE[^>]*>/gi, "");

  // Remove metadata elements
  result = result.replace(/<metadata[\s\S]*?<\/metadata>/gi, "");
  result = result.replace(/<desc[\s\S]*?<\/desc>/gi, "");
  result = result.replace(/<title[\s\S]*?<\/title>/gi, "");

  // Remove common editor-specific attributes
  const editorAttrs = [
    /\s+xmlns:xlink="[^"]*"/g,
    /\s+xmlns:dc="[^"]*"/g,
    /\s+xmlns:cc="[^"]*"/g,
    /\s+xmlns:rdf="[^"]*"/g,
    /\s+xmlns:svg="[^"]*"/g,
    /\s+xmlns:sodipodi="[^"]*"/g,
    /\s+xmlns:inkscape="[^"]*"/g,
    /\s+sodipodi:[a-z-]+=["'][^"']*["']/g,
    /\s+inkscape:[a-z-]+=["'][^"']*["']/g,
    /\s+sketch:[a-z-]+=["'][^"']*["']/g,
    /\s+data-name="[^"]*"/g,
  ];
  for (const attr of editorAttrs) {
    result = result.replace(attr, "");
  }

  // Remove empty attributes (e.g., fill="" stroke="")
  result = result.replace(/\s+[a-z-]+=["']\s*["']/g, "");

  // Trim decimal numbers to max 2 decimal places
  result = result.replace(/(\d+\.\d{3,})/g, (match) =>
    parseFloat(match).toFixed(2)
  );

  // Collapse multiple whitespace into single space
  result = result.replace(/\s{2,}/g, " ");

  // Remove whitespace between tags
  result = result.replace(/>\s+</g, "><");

  // Trim
  result = result.trim();

  return result;
}

const SAMPLE_SVG = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Inkscape -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
     xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.0.dtd"
     width="100"
     height="100"
     viewBox="0 0 100 100"
     version="1.1">
  <title>My Icon</title>
  <desc>A simple circle icon</desc>
  <metadata>
    <rdf:RDF>
      <cc:Work rdf:about="">
        <dc:format>image/svg+xml</dc:format>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <circle
    cx="50.000000"
    cy="50.000000"
    r="40.000000"
    fill="#4f46e5"
    stroke="#312e81"
    stroke-width="2.000000"
    inkscape:label="circle"
    sodipodi:nodetypes="c"
  />
  <rect
    x="20.000000"
    y="20.000000"
    width="60.000000"
    height="60.000000"
    fill=""
    opacity="0"
  />
</svg>`;

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  return `${(bytes / 1024).toFixed(2)} KB`;
}

export default function SvgOptimizerPage() {
  const MAX_INPUT_LENGTH = 5 * 1024 * 1024;
  const [input, setInput] = useState("");
  const [output, setOutput] = useState("");
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [previewTab, setPreviewTab] = useState<"original" | "optimized">("optimized");

  const optimize = useCallback(() => {
    if (!input.trim()) {
      setOutput("");
      setError("");
      return;
    }
    try {
      // Basic SVG check
      if (!input.includes("<svg")) {
        setError("Input does not appear to be valid SVG.");
        setOutput("");
        return;
      }
      const optimized = optimizeSVG(input);
      setOutput(optimized);
      setError("");
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Optimization failed.");
    }
  }, [input]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
        e.preventDefault();
        optimize();
      }
    };
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [optimize]);

  const copyOutput = async () => {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const sanitizedInput = useMemo(() => {
    if (!input) return "";
    return DOMPurify.sanitize(input, { USE_PROFILES: { svg: true, svgFilters: true } });
  }, [input]);

  const sanitizedOutput = useMemo(() => {
    if (!output) return "";
    return DOMPurify.sanitize(output, { USE_PROFILES: { svg: true, svgFilters: true } });
  }, [output]);

  const originalSize = new Blob([input]).size;
  const optimizedSize = new Blob([output]).size;
  const savings = originalSize > 0 ? Math.round(((originalSize - optimizedSize) / originalSize) * 100) : 0;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">SVG Optimizer</h1>
        <p className="text-muted-foreground mt-1">
          Remove comments, metadata, and editor artifacts from SVG files. Preview the result instantly.
        </p>
        <Badge variant="secondary" className="mt-2">
          No data sent to server
        </Badge>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm">
                SVG Input
                {input && (
                  <span className="ml-2 text-xs font-normal text-muted-foreground">
                    {formatBytes(originalSize)}
                  </span>
                )}
              </CardTitle>
              <div className="flex gap-2">
                <Button variant="ghost" size="sm" onClick={() => setInput(SAMPLE_SVG)}>
                  Sample
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => { setInput(""); setOutput(""); setError(""); }}
                >
                  Clear
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <Textarea
              placeholder="Paste your SVG code here..."
              className="font-mono text-sm min-h-[220px] resize-none"
              value={input}
              onChange={(e) => { if (e.target.value.length > MAX_INPUT_LENGTH) { alert("Input too large. Maximum size is 5MB."); return; } setInput(e.target.value); }}
            />
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm">
                Optimized Output
                {output && (
                  <span className="ml-2 text-xs font-normal text-green-400">
                    {formatBytes(optimizedSize)} — {savings}% smaller
                  </span>
                )}
              </CardTitle>
              {output && (
                <Button variant="ghost" size="sm" onClick={copyOutput}>
                  {copied ? "Copied!" : "Copy"}
                </Button>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {error ? (
              <div className="font-mono text-sm bg-red-500/10 border border-red-500/20 px-3 py-3 rounded-md text-red-400 min-h-[220px]">
                {error}
              </div>
            ) : (
              <Textarea
                readOnly
                className="font-mono text-sm min-h-[220px] resize-none"
                value={output}
                placeholder="Optimized SVG will appear here..."
              />
            )}
          </CardContent>
        </Card>
      </div>

      <div className="flex items-center gap-3">
        <Button size="lg" onClick={optimize}>
          Optimize SVG
        </Button>
        <span className="text-xs text-muted-foreground">Ctrl+Enter</span>
      </div>

      {/* SVG Preview */}
      {(input || output) && (
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm">Preview</CardTitle>
              <div className="flex gap-1">
                <Button
                  variant={previewTab === "original" ? "secondary" : "ghost"}
                  size="sm"
                  onClick={() => setPreviewTab("original")}
                >
                  Original
                </Button>
                <Button
                  variant={previewTab === "optimized" ? "secondary" : "ghost"}
                  size="sm"
                  onClick={() => setPreviewTab("optimized")}
                  disabled={!output}
                >
                  Optimized
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="flex items-center justify-center bg-muted rounded-md p-8 min-h-[160px]">
              {previewTab === "original" && sanitizedInput ? (
                <div
                  className="max-w-full max-h-40"
                  dangerouslySetInnerHTML={{ __html: sanitizedInput }}
                />
              ) : previewTab === "optimized" && sanitizedOutput ? (
                <div
                  className="max-w-full max-h-40"
                  dangerouslySetInnerHTML={{ __html: sanitizedOutput }}
                />
              ) : (
                <span className="text-muted-foreground text-sm">No preview available</span>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Related Tools */}
      <section className="py-6">
        <h2 className="text-sm font-semibold text-muted-foreground mb-3">Related Tools</h2>
        <div className="flex flex-wrap gap-2">
          {[
            { name: "CSS Gradient Generator", href: "/tools/css-gradient-generator" },
            { name: "Color Converter", href: "/tools/color-converter" },
            { name: "Base64 Encoder", href: "/tools/base64-encoder" },
            { name: "JSON Formatter", href: "/tools/json-formatter" },
          ].map((tool) => (
            <a
              key={tool.href}
              href={tool.href}
              className="text-xs px-3 py-1.5 rounded-md bg-muted hover:bg-muted/80 text-muted-foreground hover:text-foreground transition-colors"
            >
              {tool.name}
            </a>
          ))}
        </div>
      </section>

      <section className="space-y-4 py-8 border-t">
        <Tabs defaultValue="what">
          <TabsList>
            <TabsTrigger value="what">What is SVG Optimization?</TabsTrigger>
            <TabsTrigger value="how">How to Use</TabsTrigger>
            <TabsTrigger value="faq">FAQ</TabsTrigger>
          </TabsList>

          <TabsContent value="what" className="mt-4 space-y-3 text-muted-foreground text-sm">
            <h2 className="text-lg font-semibold text-foreground">What is SVG Optimization?</h2>
            <p>
              SVG files exported from design tools like Illustrator, Figma, or Inkscape contain lots of
              bloat: XML declarations, editor-specific namespaces (inkscape:, sodipodi:), metadata blocks,
              comments, and unnecessary precision in coordinates. None of this affects how the SVG renders
              in a browser, but it all adds to file size and page weight.
            </p>
            <h3 className="text-base font-semibold text-foreground">What gets removed</h3>
            <p>
              This tool removes XML declarations, comments, &lt;title&gt;, &lt;desc&gt;, and &lt;metadata&gt; elements,
              Inkscape and Sodipodi editor attributes, empty attribute values, and reduces decimal
              precision to 2 places — typically achieving 20–60% size reduction.
            </p>
          </TabsContent>

          <TabsContent value="how" className="mt-4 space-y-3 text-muted-foreground text-sm">
            <h2 className="text-lg font-semibold text-foreground">How to Use</h2>
            <ol className="list-decimal list-inside space-y-2">
              <li>Paste your SVG code into the input area, or click Sample to load an example.</li>
              <li>Click &quot;Optimize SVG&quot; or press Ctrl+Enter.</li>
              <li>See the optimized code and file size savings on the right.</li>
              <li>Use the Preview section to visually verify the SVG still looks correct.</li>
              <li>Click Copy to copy the optimized SVG.</li>
            </ol>
          </TabsContent>

          <TabsContent value="faq" className="mt-4 space-y-4 text-muted-foreground text-sm">
            <h2 className="text-lg font-semibold text-foreground">FAQ</h2>
            <div>
              <h3 className="text-sm font-semibold text-foreground">Will optimization break my SVG?</h3>
              <p>
                This tool only removes non-visual metadata and editor artifacts. The visual output
                should be identical. Always use the Preview to verify before deploying.
              </p>
            </div>
            <div>
              <h3 className="text-sm font-semibold text-foreground">Should I remove &lt;title&gt; tags?</h3>
              <p>
                For decorative icons, yes. If the SVG is used as a standalone image with accessibility
                requirements, consider keeping the title for screen reader support.
              </p>
            </div>
          </TabsContent>
        </Tabs>
      </section>
    </div>
  );
}
